<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="117687" started-at="2019-06-03T12:51:16Z" finished-at="2019-06-03T12:53:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="117687" started-at="2019-06-03T12:51:16Z" finished-at="2019-06-03T12:53:14Z">
      <class name="com.pkg.testcases.SetSystemStatus">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="beforeSuite" is-config="true" duration-ms="20540" started-at="2019-06-03T12:50:55Z" finished-at="2019-06-03T12:51:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforetest()[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="beforetest" is-config="true" duration-ms="1929" started-at="2019-06-03T12:51:16Z" finished-at="2019-06-03T12:51:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="beforeClass" is-config="true" duration-ms="1876" started-at="2019-06-03T12:51:18Z" finished-at="2019-06-03T12:51:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="postSyStemProcessTest(int)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="postSyStemProcessTest" duration-ms="10097" started-at="2019-06-03T12:51:20Z" data-provider="getID" finished-at="2019-06-03T12:51:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postSyStemProcessTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="afterMethod" is-config="true" duration-ms="6" started-at="2019-06-03T12:51:30Z" finished-at="2019-06-03T12:51:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=postSyStemProcessTest status=SUCCESS method=SetSystemStatus.postSyStemProcessTest(int)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="postSyStemProcessTest(int)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="postSyStemProcessTest" duration-ms="42835" started-at="2019-06-03T12:51:30Z" data-provider="getID" finished-at="2019-06-03T12:52:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postSyStemProcessTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="afterMethod" is-config="true" duration-ms="5" started-at="2019-06-03T12:52:13Z" finished-at="2019-06-03T12:52:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=postSyStemProcessTest status=SUCCESS method=SetSystemStatus.postSyStemProcessTest(int)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="postSyStemProcessTest(int)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="postSyStemProcessTest" duration-ms="5571" started-at="2019-06-03T12:52:13Z" data-provider="getID" finished-at="2019-06-03T12:52:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postSyStemProcessTest -->
        <test-method status="FAIL" signature="dataBaseValidation(int)[pri:1, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="dataBaseValidation" duration-ms="22805" started-at="2019-06-03T12:52:18Z" data-provider="getID" finished-at="2019-06-03T12:52:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [19] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [19] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.pkg.testcases.SetSystemStatus.dataBaseValidation(SetSystemStatus.java:174)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataBaseValidation -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-06-03T12:52:18Z" finished-at="2019-06-03T12:52:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=postSyStemProcessTest status=SUCCESS method=SetSystemStatus.postSyStemProcessTest(int)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="afterMethod" is-config="true" duration-ms="2" started-at="2019-06-03T12:52:41Z" finished-at="2019-06-03T12:52:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=dataBaseValidation status=FAILURE method=SetSystemStatus.dataBaseValidation(int)[pri:1, instance:com.pkg.testcases.SetSystemStatus@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="dataBaseValidation(int)[pri:1, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="dataBaseValidation" duration-ms="17061" started-at="2019-06-03T12:52:41Z" data-provider="getID" finished-at="2019-06-03T12:52:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.pkg.testcases.SetSystemStatus.dataBaseValidation(SetSystemStatus.java:164)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataBaseValidation -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-06-03T12:52:58Z" finished-at="2019-06-03T12:52:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=dataBaseValidation status=FAILURE method=SetSystemStatus.dataBaseValidation(int)[pri:1, instance:com.pkg.testcases.SetSystemStatus@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="dataBaseValidation(int)[pri:1, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="dataBaseValidation" duration-ms="6704" started-at="2019-06-03T12:52:58Z" data-provider="getID" finished-at="2019-06-03T12:53:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [19] but found [4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [19] but found [4]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.pkg.testcases.SetSystemStatus.dataBaseValidation(SetSystemStatus.java:174)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataBaseValidation -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="endReport" is-config="true" duration-ms="8724" started-at="2019-06-03T12:53:05Z" finished-at="2019-06-03T12:53:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.pkg.testcases.SetSystemStatus@e4487af]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-06-03T12:53:05Z" finished-at="2019-06-03T12:53:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=dataBaseValidation status=FAILURE method=SetSystemStatus.dataBaseValidation(int)[pri:1, instance:com.pkg.testcases.SetSystemStatus@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.pkg.testcases.SetSystemStatus -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
